# Generated by Django 2.0.3 on 2018-03-21 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mywork.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_auth', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('table_url', models.CharField(default=mywork.models.UUIDTools.uuid1_hex, editable=False, max_length=40)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='tablemessagemodel',
            name='table',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mywork.TableModel'),
        ),
        migrations.AddField(
            model_name='authtablemodel',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mywork.TableModel'),
        ),
        migrations.AddField(
            model_name='authtablemodel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
