# Generated by Django 2.0.3 on 2018-03-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemessagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
