# Generated by Django 2.0.3 on 2018-03-17 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_detail', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mywork.TableModel')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthTable',
        ),
    ]
