# Generated by Django 2.0.3 on 2018-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0003_auto_20180317_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtablemodel',
            name='auth_detail',
        ),
        migrations.AddField(
            model_name='authtablemodel',
            name='detail_auth',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
